from datetime import timedelta

DEBUG = True
SECRET_KEY = 'WeakSecret'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE='lax'
PERMANENT_SESSION_LIFETIME = timedelta(minutes=60)
RECAPTCHA_PUBLIC_KEY = '6LfmcrMZAAAAAJcTRMYVFIii7-reRZ4a_o5V1m37'
RECAPTCHA_PRIVATE_KEY = '6LfmcrMZAAAAAL_V-ZYV0CDySlbKLzhgi5DqYd8Q'

